### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by caiopiccirillo**
This changes will help us to check if the project compiles and if all unit tests are all OK.
I also added a pipeline that check if the code is correctly formatted. And another one for checking typos.

### CODE REVIEW

**Comment by caiopiccirillo** [comment]
Please, don't merge before https://github.com/LLagu/HAL-controller-test/pull/11, because some pipelines will change due to dependency changes.

**Comment by caiopiccirillo** [comment]
> > Please, don't merge before #11, because some pipelines will change due to dependency changes.
> 
> Should be fine now right?

Can you do me a favor? Rebase this branch on top of `main` branch and push, this will trigger the pipeline again and I expect some errors popping up.

**Comment by caiopiccirillo** [comment]
As expected a lot of errors are popping up, because we injected the protobuf dependency. If you want to dive into this, let me know. If not, I'll fix this night 😄

**Comment by LLagu** [comment]
> As expected a lot of errors are popping up, because we injected the protobuf dependency. If you want to dive into this, let me know. If not, I'll fix this night 😄

I see that it's mostly CMake related so I'll leave it to you for the moment :sweat_smile:. I'll take a look at your commits though!

**Comment by caiopiccirillo** [comment]
I tried something different here. I added support to [vcpkg](https://vcpkg.io/), which should make our lives easier regarding to dependencies. 
Locally the only change is that you'll need to rebuild your devcontainer.
Initially I was planning to add windows as a supported platform, but my lazyness won this time 😆. So we'll support only linux x64 (and armhf/armv8 crosscompile).
If you agree with the changes, you can merge.

**Pull request merged**
